#!/usr/bin/env python3
"""Convert an approved-area KML into approved_area.js for notam.html.

notam.html is opened as a file:// page, where fetch() and ES modules are blocked
by Chrome, so the overlay ships as a classic script assigning a global instead of
a .geojson fetched at runtime.

Usage: ./kml2js.py ../instrument2.kml > approved_area.js
"""

import json
import sys
import xml.etree.ElementTree as ET

KML = "http://www.opengis.net/kml/2.2"


def coords(elem):
    """KML 'lon,lat[,alt] lon,lat[,alt] ...' -> [[lon, lat], ...]"""
    if elem is None or not elem.text:
        return []
    out = []
    for tok in elem.text.split():
        parts = tok.split(",")
        if len(parts) >= 2:
            out.append([round(float(parts[0]), 6), round(float(parts[1]), 6)])
    return out


def main(path):
    root = ET.parse(path).getroot()
    features = []

    for pm in root.iter(f"{{{KML}}}Placemark"):
        name_el = pm.find(f"{{{KML}}}name")
        name = name_el.text if name_el is not None else ""

        for poly in pm.iter(f"{{{KML}}}Polygon"):
            outer = poly.find(
                f"{{{KML}}}outerBoundaryIs/{{{KML}}}LinearRing/{{{KML}}}coordinates")
            ring = coords(outer)
            if len(ring) >= 4:
                features.append({
                    "type": "Feature",
                    "properties": {"name": name, "kind": kind_of(name)},
                    "geometry": {"type": "Polygon", "coordinates": [ring]},
                })

        for line in pm.iter(f"{{{KML}}}LineString"):
            pts = coords(line.find(f"{{{KML}}}coordinates"))
            if len(pts) >= 2:
                features.append({
                    "type": "Feature",
                    "properties": {"name": name, "kind": kind_of(name)},
                    "geometry": {"type": "LineString", "coordinates": pts},
                })

    fc = {"type": "FeatureCollection", "features": features}
    sys.stdout.write("// Generated by kml2js.py -- do not edit by hand.\n")
    sys.stdout.write("// Source: %s\n" % path)
    sys.stdout.write("var APPROVED_AREA = %s;\n" % json.dumps(fc, separators=(",", ":")))


def kind_of(name):
    """Classify a placemark so notam.html can style and altitude-check it."""
    low = name.lower()
    # NFZs appear both as "NFZ_n_0" and as named "<place> NFZ_dv_0" variants.
    if "nfz" in low:
        return "nfz"
    if "flight geography" in low:
        return "flight_geography"
    if "contingency" in low:
        return "contingency"
    if "ground risk" in low:
        return "grb"
    if "altitude limit" in low or "altitude limited" in low or "crossing area" in low:
        return "altitude_limit"
    return "other"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
